# Generated by Django 5.1.1 on 2024-09-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestapp', '0003_downloadednotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='nestuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
